# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# https://github.blog/news-insights/product-news/a-faster-way-to-manage-version-updates-with-dependabot/
# https://github.blog/changelog/2021-06-16-dependabot-now-schedules-version-updates-uniformly/

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
      timezone: "Asia/Taipei"
    groups:
      actions:
        patterns:
          - "actions/*"
      docker:
        patterns:
          - "docker/*"
