name: "CI for Dispatch Workflows"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
    branches:
      - "dev/workflow*"

jobs:
  wasmedge-latest:
    uses: ./.github/workflows/wasmedge-latest.yml

  wasmedge-tags:
    uses: ./.github/workflows/wasmedge-tags.yml
    with:
      version: "0.12.1"
      repeat: 1
